import React from 'react';
import { Grid } from '@mui/material';
import { Products } from '../components/Cards/items';
import Head from 'next/head';

const Home: React.FC = () => (
  <>
    <Head>
      <title>MKS Sistemas</title>
      <meta
        name="description"
        content="Generated by create next app"
      />
    </Head>

    <Grid display="flex" direction="column">
      <Products />
    </Grid>
  </>
);

export default Home;
